
var colors = pv.Colors.category19();

var data = { nodes:
                [{nodeName: 0,
                     group: 0,
                     label:  "Mes libertés"},

                {nodeName: 1,
                     group: 1,
                      label:  "Internet"},
                {nodeName: 2,
                     group: 1,
                      label:  "Fichier"},
                {nodeName: 3,
                     group: 1,
                     label:  "Habitation"},
                {nodeName: 4,
                     group: 1,
                     label:  "Délation"},
                {nodeName: 5,
                     group: 1,
                     label:  "Instituion"},
                {nodeName: 6,
                     group: 1,
                     label:  "Pouvoirs Policiers"},
                {nodeName: 7,
                     group: 1,
                     label:  "Prison"},
                {nodeName: 8,
                     group: 1,
                     label:  "Nouveaux Délits"},
                {nodeName: 9,
                     group: 1,
                     label:  "Chronologie"},
                {nodeName: 10,
                     group: 1,
                     label:  "Étrangers"},
                {nodeName: 11,
                     group: 1,
                     label:  "Suspicion"} ],

             links : [
                 {source:0, target:1, value:1},
                 {source:0, target:2, value:1},
                 {source:0, target:3, value:1},
                 {source:0, target:4, value:1},
                 {source:0, target:5, value:1},
                 {source:0, target:6, value:1},
                 {source:0, target:7, value:1},
                 {source:0, target:8, value:1},
                 {source:0, target:9, value:1},
                 {source:0, target:10, value:1},
                 {source:0, target:11, value:1} ]
            };